### ISSUE TITLE
scenario.sleep(): actually sleeps only if in dry-run mode

### ISSUE THREAD

**Issue by pini-edf** [edf-hpc/neos#15]
As I understand it this [sleep()](https://github.com/edf-hpc/neos/blob/aedef4e3133cc57e85ec8c828abc8b2db502e500/neos/scenario.py#L127) method actually does the contrary of what its docstring says:
```
    def sleep(self, time):
        """Sleep if not in dry-run mode."""
        if self.conf.dryrun:
            sleep(time)
```

**Comment by rezib** [comment]
Nice catch! The docstring is right, the code is wrong.
